#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import sys, os, codecs
import argparse, textwrap
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/../')

from sqlearn.corpus import brat

if __name__ == '__main__':
  parser = argparse.ArgumentParser(
    formatter_class=argparse.RawDescriptionHelpFormatter,
    description=textwrap.dedent('''
      tagging
    ''')
  )
  
  parser.add_argument('raw', type=str, help='')
  parser.add_argument('ann', type=str, help='')
  
  args = parser.parse_args()
  
  brat.conv_conll(args.raw, args.ann)
